/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as GuestIndexRouteImport } from './routes/_guest/index'
import { Route as GuestWipRouteImport } from './routes/_guest/wip'
import { Route as GuestFormRouteImport } from './routes/_guest/_form'
import { Route as AuthenticatedVerifyEmailRouteImport } from './routes/_authenticated/verify-email'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMyWorkRouteImport } from './routes/_authenticated/my-work'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTicketsRouteRouteImport } from './routes/_authenticated/tickets/route'
import { Route as GuestFormTwoFactorChallengeRouteImport } from './routes/_guest/_form/two-factor-challenge'
import { Route as GuestFormResetPasswordRouteImport } from './routes/_guest/_form/reset-password'
import { Route as GuestFormRegisterRouteImport } from './routes/_guest/_form/register'
import { Route as GuestFormLoginRouteImport } from './routes/_guest/_form/login'
import { Route as GuestFormForgotPasswordRouteImport } from './routes/_guest/_form/forgot-password'
import { Route as AuthenticatedTicketsTicketIdRouteImport } from './routes/_authenticated/tickets/$ticketId'
import { Route as AuthenticatedTeamsTeamIdTicketsRouteImport } from './routes/_authenticated/teams/$teamId/tickets'
import { Route as AuthenticatedProjectsProjectIdTicketsRouteImport } from './routes/_authenticated/projects/$projectId/tickets'
import { Route as AuthenticatedTeamsTeamIdTicketsTicketIdRouteImport } from './routes/_authenticated/teams/$teamId/tickets.$ticketId'
import { Route as AuthenticatedProjectsProjectIdTicketsTicketIdRouteImport } from './routes/_authenticated/projects/$projectId/tickets.$ticketId'

const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestIndexRoute = GuestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuestRoute,
} as any)
const GuestWipRoute = GuestWipRouteImport.update({
  id: '/wip',
  path: '/wip',
  getParentRoute: () => GuestRoute,
} as any)
const GuestFormRoute = GuestFormRouteImport.update({
  id: '/_form',
  getParentRoute: () => GuestRoute,
} as any)
const AuthenticatedVerifyEmailRoute =
  AuthenticatedVerifyEmailRouteImport.update({
    id: '/verify-email',
    path: '/verify-email',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyWorkRoute = AuthenticatedMyWorkRouteImport.update({
  id: '/my-work',
  path: '/my-work',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTicketsRouteRoute =
  AuthenticatedTicketsRouteRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const GuestFormTwoFactorChallengeRoute =
  GuestFormTwoFactorChallengeRouteImport.update({
    id: '/two-factor-challenge',
    path: '/two-factor-challenge',
    getParentRoute: () => GuestFormRoute,
  } as any)
const GuestFormResetPasswordRoute = GuestFormResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => GuestFormRoute,
} as any)
const GuestFormRegisterRoute = GuestFormRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => GuestFormRoute,
} as any)
const GuestFormLoginRoute = GuestFormLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestFormRoute,
} as any)
const GuestFormForgotPasswordRoute = GuestFormForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => GuestFormRoute,
} as any)
const AuthenticatedTicketsTicketIdRoute =
  AuthenticatedTicketsTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => AuthenticatedTicketsRouteRoute,
  } as any)
const AuthenticatedTeamsTeamIdTicketsRoute =
  AuthenticatedTeamsTeamIdTicketsRouteImport.update({
    id: '/teams/$teamId/tickets',
    path: '/teams/$teamId/tickets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdTicketsRoute =
  AuthenticatedProjectsProjectIdTicketsRouteImport.update({
    id: '/projects/$projectId/tickets',
    path: '/projects/$projectId/tickets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeamsTeamIdTicketsTicketIdRoute =
  AuthenticatedTeamsTeamIdTicketsTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => AuthenticatedTeamsTeamIdTicketsRoute,
  } as any)
const AuthenticatedProjectsProjectIdTicketsTicketIdRoute =
  AuthenticatedProjectsProjectIdTicketsTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => AuthenticatedProjectsProjectIdTicketsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/tickets': typeof AuthenticatedTicketsRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-work': typeof AuthenticatedMyWorkRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/verify-email': typeof AuthenticatedVerifyEmailRoute
  '/wip': typeof GuestWipRoute
  '/': typeof GuestIndexRoute
  '/tickets/$ticketId': typeof AuthenticatedTicketsTicketIdRoute
  '/forgot-password': typeof GuestFormForgotPasswordRoute
  '/login': typeof GuestFormLoginRoute
  '/register': typeof GuestFormRegisterRoute
  '/reset-password': typeof GuestFormResetPasswordRoute
  '/two-factor-challenge': typeof GuestFormTwoFactorChallengeRoute
  '/projects/$projectId/tickets': typeof AuthenticatedProjectsProjectIdTicketsRouteWithChildren
  '/teams/$teamId/tickets': typeof AuthenticatedTeamsTeamIdTicketsRouteWithChildren
  '/projects/$projectId/tickets/$ticketId': typeof AuthenticatedProjectsProjectIdTicketsTicketIdRoute
  '/teams/$teamId/tickets/$ticketId': typeof AuthenticatedTeamsTeamIdTicketsTicketIdRoute
}
export interface FileRoutesByTo {
  '/tickets': typeof AuthenticatedTicketsRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-work': typeof AuthenticatedMyWorkRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/verify-email': typeof AuthenticatedVerifyEmailRoute
  '/wip': typeof GuestWipRoute
  '/': typeof GuestIndexRoute
  '/tickets/$ticketId': typeof AuthenticatedTicketsTicketIdRoute
  '/forgot-password': typeof GuestFormForgotPasswordRoute
  '/login': typeof GuestFormLoginRoute
  '/register': typeof GuestFormRegisterRoute
  '/reset-password': typeof GuestFormResetPasswordRoute
  '/two-factor-challenge': typeof GuestFormTwoFactorChallengeRoute
  '/projects/$projectId/tickets': typeof AuthenticatedProjectsProjectIdTicketsRouteWithChildren
  '/teams/$teamId/tickets': typeof AuthenticatedTeamsTeamIdTicketsRouteWithChildren
  '/projects/$projectId/tickets/$ticketId': typeof AuthenticatedProjectsProjectIdTicketsTicketIdRoute
  '/teams/$teamId/tickets/$ticketId': typeof AuthenticatedTeamsTeamIdTicketsTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_authenticated/tickets': typeof AuthenticatedTicketsRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/my-work': typeof AuthenticatedMyWorkRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/verify-email': typeof AuthenticatedVerifyEmailRoute
  '/_guest/_form': typeof GuestFormRouteWithChildren
  '/_guest/wip': typeof GuestWipRoute
  '/_guest/': typeof GuestIndexRoute
  '/_authenticated/tickets/$ticketId': typeof AuthenticatedTicketsTicketIdRoute
  '/_guest/_form/forgot-password': typeof GuestFormForgotPasswordRoute
  '/_guest/_form/login': typeof GuestFormLoginRoute
  '/_guest/_form/register': typeof GuestFormRegisterRoute
  '/_guest/_form/reset-password': typeof GuestFormResetPasswordRoute
  '/_guest/_form/two-factor-challenge': typeof GuestFormTwoFactorChallengeRoute
  '/_authenticated/projects/$projectId/tickets': typeof AuthenticatedProjectsProjectIdTicketsRouteWithChildren
  '/_authenticated/teams/$teamId/tickets': typeof AuthenticatedTeamsTeamIdTicketsRouteWithChildren
  '/_authenticated/projects/$projectId/tickets/$ticketId': typeof AuthenticatedProjectsProjectIdTicketsTicketIdRoute
  '/_authenticated/teams/$teamId/tickets/$ticketId': typeof AuthenticatedTeamsTeamIdTicketsTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/tickets'
    | '/dashboard'
    | '/my-work'
    | '/settings'
    | '/verify-email'
    | '/wip'
    | '/'
    | '/tickets/$ticketId'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/two-factor-challenge'
    | '/projects/$projectId/tickets'
    | '/teams/$teamId/tickets'
    | '/projects/$projectId/tickets/$ticketId'
    | '/teams/$teamId/tickets/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/tickets'
    | '/dashboard'
    | '/my-work'
    | '/settings'
    | '/verify-email'
    | '/wip'
    | '/'
    | '/tickets/$ticketId'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/two-factor-challenge'
    | '/projects/$projectId/tickets'
    | '/teams/$teamId/tickets'
    | '/projects/$projectId/tickets/$ticketId'
    | '/teams/$teamId/tickets/$ticketId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_guest'
    | '/_authenticated/tickets'
    | '/_authenticated/dashboard'
    | '/_authenticated/my-work'
    | '/_authenticated/settings'
    | '/_authenticated/verify-email'
    | '/_guest/_form'
    | '/_guest/wip'
    | '/_guest/'
    | '/_authenticated/tickets/$ticketId'
    | '/_guest/_form/forgot-password'
    | '/_guest/_form/login'
    | '/_guest/_form/register'
    | '/_guest/_form/reset-password'
    | '/_guest/_form/two-factor-challenge'
    | '/_authenticated/projects/$projectId/tickets'
    | '/_authenticated/teams/$teamId/tickets'
    | '/_authenticated/projects/$projectId/tickets/$ticketId'
    | '/_authenticated/teams/$teamId/tickets/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/': {
      id: '/_guest/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GuestIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/wip': {
      id: '/_guest/wip'
      path: '/wip'
      fullPath: '/wip'
      preLoaderRoute: typeof GuestWipRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/_form': {
      id: '/_guest/_form'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GuestFormRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_authenticated/verify-email': {
      id: '/_authenticated/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthenticatedVerifyEmailRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-work': {
      id: '/_authenticated/my-work'
      path: '/my-work'
      fullPath: '/my-work'
      preLoaderRoute: typeof AuthenticatedMyWorkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_guest/_form/two-factor-challenge': {
      id: '/_guest/_form/two-factor-challenge'
      path: '/two-factor-challenge'
      fullPath: '/two-factor-challenge'
      preLoaderRoute: typeof GuestFormTwoFactorChallengeRouteImport
      parentRoute: typeof GuestFormRoute
    }
    '/_guest/_form/reset-password': {
      id: '/_guest/_form/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof GuestFormResetPasswordRouteImport
      parentRoute: typeof GuestFormRoute
    }
    '/_guest/_form/register': {
      id: '/_guest/_form/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof GuestFormRegisterRouteImport
      parentRoute: typeof GuestFormRoute
    }
    '/_guest/_form/login': {
      id: '/_guest/_form/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestFormLoginRouteImport
      parentRoute: typeof GuestFormRoute
    }
    '/_guest/_form/forgot-password': {
      id: '/_guest/_form/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof GuestFormForgotPasswordRouteImport
      parentRoute: typeof GuestFormRoute
    }
    '/_authenticated/tickets/$ticketId': {
      id: '/_authenticated/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof AuthenticatedTicketsTicketIdRouteImport
      parentRoute: typeof AuthenticatedTicketsRouteRoute
    }
    '/_authenticated/teams/$teamId/tickets': {
      id: '/_authenticated/teams/$teamId/tickets'
      path: '/teams/$teamId/tickets'
      fullPath: '/teams/$teamId/tickets'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdTicketsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/tickets': {
      id: '/_authenticated/projects/$projectId/tickets'
      path: '/projects/$projectId/tickets'
      fullPath: '/projects/$projectId/tickets'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdTicketsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teams/$teamId/tickets/$ticketId': {
      id: '/_authenticated/teams/$teamId/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/teams/$teamId/tickets/$ticketId'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdTicketsTicketIdRouteImport
      parentRoute: typeof AuthenticatedTeamsTeamIdTicketsRoute
    }
    '/_authenticated/projects/$projectId/tickets/$ticketId': {
      id: '/_authenticated/projects/$projectId/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/projects/$projectId/tickets/$ticketId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdTicketsTicketIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdTicketsRoute
    }
  }
}

interface AuthenticatedTicketsRouteRouteChildren {
  AuthenticatedTicketsTicketIdRoute: typeof AuthenticatedTicketsTicketIdRoute
}

const AuthenticatedTicketsRouteRouteChildren: AuthenticatedTicketsRouteRouteChildren =
  {
    AuthenticatedTicketsTicketIdRoute: AuthenticatedTicketsTicketIdRoute,
  }

const AuthenticatedTicketsRouteRouteWithChildren =
  AuthenticatedTicketsRouteRoute._addFileChildren(
    AuthenticatedTicketsRouteRouteChildren,
  )

interface AuthenticatedProjectsProjectIdTicketsRouteChildren {
  AuthenticatedProjectsProjectIdTicketsTicketIdRoute: typeof AuthenticatedProjectsProjectIdTicketsTicketIdRoute
}

const AuthenticatedProjectsProjectIdTicketsRouteChildren: AuthenticatedProjectsProjectIdTicketsRouteChildren =
  {
    AuthenticatedProjectsProjectIdTicketsTicketIdRoute:
      AuthenticatedProjectsProjectIdTicketsTicketIdRoute,
  }

const AuthenticatedProjectsProjectIdTicketsRouteWithChildren =
  AuthenticatedProjectsProjectIdTicketsRoute._addFileChildren(
    AuthenticatedProjectsProjectIdTicketsRouteChildren,
  )

interface AuthenticatedTeamsTeamIdTicketsRouteChildren {
  AuthenticatedTeamsTeamIdTicketsTicketIdRoute: typeof AuthenticatedTeamsTeamIdTicketsTicketIdRoute
}

const AuthenticatedTeamsTeamIdTicketsRouteChildren: AuthenticatedTeamsTeamIdTicketsRouteChildren =
  {
    AuthenticatedTeamsTeamIdTicketsTicketIdRoute:
      AuthenticatedTeamsTeamIdTicketsTicketIdRoute,
  }

const AuthenticatedTeamsTeamIdTicketsRouteWithChildren =
  AuthenticatedTeamsTeamIdTicketsRoute._addFileChildren(
    AuthenticatedTeamsTeamIdTicketsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedTicketsRouteRoute: typeof AuthenticatedTicketsRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMyWorkRoute: typeof AuthenticatedMyWorkRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedVerifyEmailRoute: typeof AuthenticatedVerifyEmailRoute
  AuthenticatedProjectsProjectIdTicketsRoute: typeof AuthenticatedProjectsProjectIdTicketsRouteWithChildren
  AuthenticatedTeamsTeamIdTicketsRoute: typeof AuthenticatedTeamsTeamIdTicketsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedTicketsRouteRoute: AuthenticatedTicketsRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMyWorkRoute: AuthenticatedMyWorkRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedVerifyEmailRoute: AuthenticatedVerifyEmailRoute,
  AuthenticatedProjectsProjectIdTicketsRoute:
    AuthenticatedProjectsProjectIdTicketsRouteWithChildren,
  AuthenticatedTeamsTeamIdTicketsRoute:
    AuthenticatedTeamsTeamIdTicketsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface GuestFormRouteChildren {
  GuestFormForgotPasswordRoute: typeof GuestFormForgotPasswordRoute
  GuestFormLoginRoute: typeof GuestFormLoginRoute
  GuestFormRegisterRoute: typeof GuestFormRegisterRoute
  GuestFormResetPasswordRoute: typeof GuestFormResetPasswordRoute
  GuestFormTwoFactorChallengeRoute: typeof GuestFormTwoFactorChallengeRoute
}

const GuestFormRouteChildren: GuestFormRouteChildren = {
  GuestFormForgotPasswordRoute: GuestFormForgotPasswordRoute,
  GuestFormLoginRoute: GuestFormLoginRoute,
  GuestFormRegisterRoute: GuestFormRegisterRoute,
  GuestFormResetPasswordRoute: GuestFormResetPasswordRoute,
  GuestFormTwoFactorChallengeRoute: GuestFormTwoFactorChallengeRoute,
}

const GuestFormRouteWithChildren = GuestFormRoute._addFileChildren(
  GuestFormRouteChildren,
)

interface GuestRouteChildren {
  GuestFormRoute: typeof GuestFormRouteWithChildren
  GuestWipRoute: typeof GuestWipRoute
  GuestIndexRoute: typeof GuestIndexRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestFormRoute: GuestFormRouteWithChildren,
  GuestWipRoute: GuestWipRoute,
  GuestIndexRoute: GuestIndexRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
